service: serverless

provider:
  name: aws
  runtime: nodejs12.x
  profile: slstest
  region: ap-south-1
  stage: dev
  
plugins:
  - serverless-offline

functions:  
  api:
    handler: src/api/api.handler
    events:
      - http:
          path: /api
          method: get
          cors: true
  todos:
    handler: src/api/todos.handler
    events:
      - http:
          path: /todo
          method: get
  todo:
    handler: src/api/todo.handler
    events:
      - http:
          path: /todo/{id}
          method: get
